title:              Alastair Burniston
email:              contact@alastairb.co.uk
description:        Online Portfolio
author:             Alastair Burniston
baseurl:            ""
url:                "https://alastairb.co.uk"

# Social Profiles
instagram_username: talos.designs
linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
